services:
  - type: web
    name: calorie-tracker-api
    env: node
    region: frankfurt
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000